version: "3.6"
services:

  openindoor-rex:
    build:
      context: .
    image: openindoor/openindoor-rex
    # command: serve --openbrowser=false --config=myconfig.toml
    environment:
      POSTGRES_DB: openindoor-db
      POSTGRES_USER: openindoor-db-admin
      POSTGRES_PASSWORD: admin123
    volumes:
    - ./myconfig.toml:/var/data/in/myconfig.toml
    - ./test/in:/var/data/in:ro
    - ./test/out:/var/data/out
    ports:
    - 6767:6767

